// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { SideNav } from "./side-nave";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full max-w-6xl mx-auto pt-12 min-h-screen px-4">
      <div className="flex gap-8">
        <SideNav />
        <div className="flex-1 min-w-0">
          <div className="bg-white/20 backdrop-blur-md rounded-2xl shadow-2xl p-8 min-h-[60vh]">
            {children}
          </div>
        </div>
      </div>
    </main>
  );
}